### ISSUE TITLE
Support for window.caches

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/gangway#39]
Part of the [service worker spec](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) includes a caching API Should we do this?

https://developer.mozilla.org/en-US/docs/Web/API/Window/caches

What would it look like to provide sugar for defining caching policies?

cc @brianjlandau @mackermedia @greypants

**Comment by brianjlandau** [comment]
Seems very cool, but seems very new, not well supported and the spec is still a work in progress. My analysis: this seems a little fringe to be using just yet.

**Comment by nhunzaker** [comment]
@brianjlandau Fair. But caching has come up in the past. Is the feature itself an useful one?

**Comment by brianjlandau** [comment]
Well caching would be useful yes. How is it decided when these caches expire? Or how do you tell it? Can you give it a TTL?

**Comment by nhunzaker** [comment]
Yeah. Hard call. I'm fine waiting on this until I know more about the cache api that comes with [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).
